all:
  hosts:
    node1:
      ansible_host: 192.168.30.23
      ip: 192.168.30.23
      access_ip: 192.168.30.23
    node2:
      ansible_host: 192.168.30.7
      ip: 192.168.30.7
      access_ip: 192.168.30.7
    node3:
      ansible_host: 192.168.30.17
      ip: 192.168.30.17
      access_ip: 192.168.30.17
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
